server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: user
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
      exposure:
        include: 'info,health'
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: false
    show-sql: true
---
spring:
  main:
    allow-bean-definition-overriding: true
